#!/usr/bin/env bash

source .setup/helpers

# warn
printf "This script is supposed to be executed only once in order to populate the dotfiles
repo from the available files across the current system. If you run it after the
files are symlinked, you're just copying dead symlinks over symlinks. That'd be
genocide, be warned.\n\n"
read -p "Press enter to continue..."

# collect non-symlinked dotfiles
./update

# package managers
say 'Collecting npm, gem, pip and composer configs, if any...'
cp -vf ~/.gemrc ruby/
cp -vf ~/.npmrc node/
cp -vf ~/.composer/composer.json php/

# shell
say 'Collecting shell files...'
cp -vf ~/.profile shell/
cp -vf ~/.zshrc shell/zsh/
cp -vf ~/.{bashrc,bash_profile} shell/bash/

# editors
say 'Collecting editor configs...'
cp -vf ~/.{vimrc,vundle.vim} editors/vim/
cp -vf ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/* editors/sublime/
git submodule add https://github.com/sepehr/intellij-settings.git editor/intellij

# git
say 'Collecting git configs...'
cp -vf ~/.{gitconfig,gitignore,gitignore_global} git/

# ssh/gpg
say 'Collecting ssh/gpg configs...'
cp -vf ~/.ssh/config ssh/config
cp -vf ~/.gnupg/gpg.conf gnupg/gpg.conf

# terminal
say 'Collecting terminal configs...'
cp -vf ~/.hyper.js terminal/hyper/

# misc
say 'Collecting misc configs...'
cp -vf ~/.{ackrc,axelrc,mongorc.js} etc/
cp -vf ~/Library/Application\ Support/Google/Chrome/Profile\ 2/databases/chrome-extension_fjnbnpbmkenffdnngjfgmeleoegfcffe_0/1 etc/stylish.sqlite
