#!/usr/bin/env bash

source .setup/helpers

## warn
printf "
This script is supposed to be executed only once in order to populate the dotfiles
repo from the available files across the current system. If you run it after the
files are symlinked, you're just copying dead symlinks over symlinks. That'd be
genocide, be warned.\n\n"
read -p "Press enter to continue..."
read -p "Re-read the above, are you damn sure?"
read -p "Read the above again, are you fuckin damn sure?"
read -p "Just checkin for the last time, sure?"


## collect non-symlinked dotfiles
./update


## privates
say 'Collecting privates...'

# todos
cp -vf ~/.todos.json private/conf

# hosts
cp -vf /etc/hosts private/etc

# shell
cp -vf ~/.zshrc.local private/conf/shell
cp -vf ~/.bashrc.local private/conf/shell
cp -vf ~/.profile.local private/conf/shell

# confs
cp -vf ~/.githubrc private/conf

# apps
# well, not anymore.

# personal content
cp -rf ~/Pictures/{Etc,Icons,Identity,Photos,Wallpapers,Photo\ Booth\ Library} private/var/pictures

# macos prefs
# let's not litter the cloud.
#cp -rf ~/Library/Preferences private/conf/macos


## shell
say 'Collecting shell files...'
cp -vf ~/.{zshrc,profile,profile.helpers,profile.path,aliases,bashrc,bash_profile} conf/shell/


## languages
say 'Collecting npm, gem, pip, pyenv, rbenv and composer configs, if any...'
cp -vf ~/.gemrc conf/
cp -vf ~/.npmrc conf/
./bin/composer-global-collect


## git/ssh/gpg
say 'Collecting git, ssh and gpg configs...'
cp -vf ~/.ssh/config conf/ssh/config
cp -vf ~/.gnupg/gpg.conf conf/gnupg/gpg.conf
cp -vf ~/.gnupg/gpg-agent.conf conf/gnupg/gpg-agent.conf
cp -vf ~/.{gitconfig,gitignore,gitignore_global,git_hooks} conf/git/


## misc
say 'Collecting misc configs...'
cp -vf ~/.translate-shell/init.trans conf/trans.init
cp -vf ~/.{ackrc,curlrc,axelrc,mongorc.js,editorconfig,ansible.cfg} conf/


## services
say 'Collecting service configs...'

# supervisor
cp -vf /usr/local/etc/supervisord.ini conf/service/supervisor
cp -vrf /usr/local/etc/supervisor.d conf/service/supervisor/supervisor.d

# apache httpd
cp -vf /usr/local/etc/httpd/httpd.conf conf/service/httpd/
cp -vf /usr/local/etc/httpd/extra/httpd-vhosts.conf conf/service/httpd/

# php
cp -rf /usr/local/etc/php/5.6/conf.d conf/service/php/5.6
cp -vf /usr/local/etc/php/5.6/{php.ini,php-fpm.conf} conf/service/php/5.6


cp -rf /usr/local/etc/php/7.3/conf.d conf/service/php/7.3
cp -rf /usr/local/etc/php/7.3/php-fpm.d conf/service/php/7.3
cp -vf /usr/local/etc/php/7.3/{php.ini,php-fpm.conf} conf/service/php/7.3

# valet
cp -vf ~/.config/valet/config.json conf/service/valet/config.json

# homestead
cp -vf ~/.homestead/{Homestead.yaml,Vagrantfile,after.sh} conf/service/homestead

# nginx
cp -rf /usr/local/etc/nginx/{valet,servers} conf/service/nginx
cp -vf /usr/local/etc/nginx/{nginx.conf,fastcgi_params} conf/service/nginx

# dnsmasq
cp -vf /usr/local/etc/dnsmasq.conf conf/service/dnsmasq

# mysql/mariadb
cp -vf /usr/local/etc/my.cnf conf/service/mysql

## apps
say 'Collecting app configs...'

# intellij repo
git submodule add https://github.com/sepehr/intellij-settings.git conf/app/intellij

# vim
mkdir -p conf/app/vim/.vim
cp -rf ~/.vim/{autoload,colors} conf/app/vim/.vim
cp -vf ~/.{vimrc,.vimrc_background,gvimrc} conf/app/vim/

# sublime
cp -rf ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/{Schemes,Preferences.sublime-settings,Default\ \(OSX\).sublime-keymap,Package\ Control.sublime-settings,Default\ \(OSX\).sublime-mousemap} conf/app/sublime

# dash
cp -vf ~/Library/Application\ Support/Dash/library.dash conf/app/dash

# littlesnitch
cp -vf ~/Library/Application\ Support/Little\ Snitch/configuration.user.xpl conf/app/littlesnitch

# apptivate
cp -vf ~/Library/Application\ Support/Apptivate/hotkeys conf/app/apptivate

# gifhunter
cp -vf ~/Library/Containers/io.madebyw.GIFHunter/Data/Library/Application\ Support/io.madebyw.GIFHunter/archive.data conf/app/gifhunter/archive.plist
