#!/usr/bin/env sh

source .setup/helpers

## Root symlink
# Usage: mkln [existing-source] [target-to-remove-and-symlink]
say 'Symlinking with root privilage...'

# /etc/hosts file
# WARNING: dnsmasq will fail to load a symlinked hosts file
# mkln ~/.dotfiles/private/etc/hosts /etc/hosts

# macos prefs
# NOTE: ~/Library/Preferences will be synced manually as part of ./update script to avoid high CPU usage
# mkln ~/.dotfiles/private/conf/macos/Preferences ~/Library/Preferences
