#!/usr/bin/env bash

printf "
This script sets up the machine by installing various packages and applications
from external sources. It will take a shit load of time. You're warned.

The script will ask your password as it needs to do operations that need root
privilage...\n\n"
read -p "Press enter to continue..."

source .setup/helpers

say 'Setting google dns servers for Wi-Fi interface...'
sudo networksetup -setdnsservers AirPort 8.8.8.8 8.8.4.4

# See: https://github.com/drduh/macOS-Security-and-Privacy-Guide#captive-portal
say 'Disabling captive portal...'
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.captive.control Active -bool false

say 'Downloading keyservers CA certificate for gnupg2...'
mkdir -p /usr/local/etc/ssl/certs
wget https://sks-keyservers.net/sks-keyservers.netCA.pem -O /usr/local/etc/ssl/certs/hkps.pool.sks-keyservers.net.pem

say 'Setting proper permissions for /usr/local directory...'
sudo chown -R $(whoami):admin /usr/local

say 'Installing brew, if necessary...'
if ! command -v brew &> /dev/null; then
    xcode-select --install
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

say 'Tapping & installing brew bundler...'
brew tap homebrew/bundle

say 'Tapping & installing repos, packages and casks from file...'
brew bundle --file=brew/brewfile

say 'Setting zsh as the default shell...'
ZSH_PATH=$(which zsh)
grep -q "$ZSH_PATH" /etc/shells || sudo sh -c "echo '$ZSH_PATH' >> /etc/shells"
chsh -s $ZSH_PATH

say 'Installing global pip packages from file...'
pip install -U -r python/pipfile

say 'Installing global gem packages from file...'
xargs gem install < ruby/gemfile

say 'Installing global npm packages...'
xargs npm install --global < node/npmfile

say 'Installing global composer packages...'
composer global install

say 'Installing apm packages...'
apm install --packages-file editor/atom/apmfile
