#!/usr/bin/env bash

source .setup/helpers

## brew
say 'Collecting brew taps, packages, casks and mas apps...'
rm -f cellar/brewfile
brew bundle dump --file=cellar/brewfile

## pip
say 'Collecting pip global packages...'
pip2 freeze > cellar/pip2file
pip3 freeze > cellar/pip3file

## gem
say 'Collecting gem global packages...'
gem list --no-versions | sed '/^*/ d' > cellar/gemfile

## npm
say 'Collecting npm global packages...'
npm list --global --parseable --depth=0 | sed '1d' | awk '{gsub(/\/.*\//,"",$1); print}' > cellar/npmfile

## apm
say 'Collecting apm packages...'
apm list --installed --bare > cellar/apmfile

## etc
say 'Collecting /etc/hosts file...'
cp -f /etc/hosts private/etc

say 'Collecting apptivate hotkeys...'
cp -f ~/Library/Application\ Support/Apptivate/hotkeys conf/app/apptivate

say 'Syncing macOS preferences...'
sudo rsync -au --delete ~/Library/Preferences/ private/conf/macos/Preferences/

say 'Cleaning up...'
rm -f private/conf/app/adium/Adium\ 2.0/Users/Default/libpurple/telegram-purple/+19706737347/downloads/*
