#!/usr/bin/env bash

source .setup/helpers

## mas apps
if [[ "$@" != *"--no-mas"* ]]; then
    say 'Upgrading mas apps...'
    mas upgrade
fi

## brew
if [[ "$@" != *"--no-brew"* ]]; then
    say 'Upgrading brew formulaes...'
    brew upgrade
fi

## brew cask
if [[ "$@" != *"--no-cask"* ]]; then
    say 'Upgrading essential brew casks...'
    brew cask reinstall appcleaner devrantron filezilla firefox google-chrome google-chrome-canary iina iterm2-nightly kap macpass postman skype spotify torbrowser vlc knockknock blockblock ransomwhere kextviewr tunnelblick vagrant virtualbox
fi

## composer
if [[ "$@" != *"--no-composer"* ]]; then
    say 'Upgrading global composer packages...'
    composer global update
fi

## npm
if [[ "$@" != *"--no-npm"* ]]; then
    say 'Upgrading global npm packages...'
    npm -g upgrade
fi

## apm
if [[ "$@" != *"--no-apm"* ]]; then
    say 'Upgrading apm packages...'
    apm upgrade --no-confirm
fi

## gem
if [[ "$@" != *"--no-gem"* ]]; then
    say 'Upgrading global gems...'
    gem update
fi

## pip
if [[ "$@" != *"--no-pip"* ]]; then
    say 'Upgrading global pip packages...'
    ./bin/pip-update
fi

## vagrant
if [[ "$@" != *"--no-vagrant"* ]]; then
    say 'Upgrading vagrant plugins...'
    vagrant plugin update
fi

## zplug
if [[ "$@" != *"--no-zplug"* ]]; then
    say 'Upgrading zplug plugins...'
    zplug update
fi

## recollect
if [[ "$@" != *"--no-recollect"* ]]; then
    say 'Now, recollecting everything for you...'
    ./update > /dev/null 2>&1
fi

## cleanup
if [[ "$@" != *"--no-cleanup"* ]]; then
    say 'Cleaning up...'
    brew cleanup -s
    brew cask cleanup
    sudo purge
fi
