#!/usr/bin/env bash

source .setup/helpers

## mas apps
if [[ "$@" != *"--no-mas"* ]]; then
    say 'Upgrading mas apps...'
    mas upgrade
fi

## brew
# this can cause incompatibility issues, watch out.
if [[ "$@" != *"--no-brew"* ]]; then
    say 'Upgrading brew formulaes...'
    brew upgrade
fi

## brew cask
if [[ "$@" != *"--no-cask"* ]]; then
    say 'Upgrading essential brew casks...'

    brew cask reinstall appcleaner filezilla firefox google-chrome google-chrome-canary iina iterm2-nightly kap macpass postman skype torbrowser transmission vlc knockknock blockblock ransomwhere kextviewr tunnelblick
fi

## virtualbox/vagrant
if [[ "$@" != *"--no-virtualbox"* ]]; then
    say 'Upgrading virtualbox/vagrant and the plugins...'

    vagrant halt all
    pkill VBox

    brew cask reinstall virtualbox vagrant

    # `vagrant plugin update` might not work in case of vagrant upgrades
    # In case of failed reinstallation, look into cellar/vagrant for missing plugins
    # The minimum requirements are: vagrant-share, vagrant-vbguest
    vagrant plugin expunge --reinstall --force
fi

## composer
if [[ "$@" != *"--no-composer"* ]]; then
    say 'Upgrading global composer packages...'
    composer global update
    composer global bin all update
fi

## npm
if [[ "$@" != *"--no-npm"* ]]; then
    say 'Upgrading global npm packages...'
    npm -g upgrade
fi

## apm
if [[ "$@" != *"--no-apm"* ]]; then
    say 'Upgrading apm packages...'
    apm upgrade --no-confirm
fi

## gem
if [[ "$@" != *"--no-gem"* ]]; then
    say 'Upgrading global gems...'
    gem update
fi

## pip
if [[ "$@" != *"--no-pip"* ]]; then
    say 'Upgrading global pip packages...'
    ./bin/pip-update
fi

## zplug
if [[ "$@" != *"--no-zplug"* ]]; then
    say 'Upgrading zplug plugins...'
    source $ZPLUG_HOME/init.zsh
    zplug update
    zplug clean

    say 'Upgrading zplug itself...'
    git -C $ZPLUG_HOME pull origin master > /dev/null 2>&1
fi

## recollect
if [[ "$@" != *"--no-recollect"* ]]; then
    say 'Now, recollecting everything for you...'
    ./update > /dev/null 2>&1
fi

## cleanup
if [[ "$@" != *"--no-cleanup"* ]]; then
    say 'Cleaning up...'
    brew cleanup -s
    brew cask cleanup
    sudo purge
    yarn cache clean > /dev/null 2>&1
fi
